### PR TITLE
Make node pool taint non-mandatory

### PR DESCRIPTION
**Pull request by katiekeel**

### CODE REVIEW

**Comment by katiekeel** [comment]
@sudermanjr Hope you enjoyed my string of increasingly deranged commit messages. At least 3 of those were during an hour I spent editing the wrong file and going insane... But this works for sure now, for clusters with both tainted and untainted nodes.

Still haven't looked how to version it; will do that shortly

**Comment by katiekeel** [comment]
@lucasreed Andy requested you approve this when you get time.

**Review by lucasreed — CHANGES_REQUESTED** [review]
I like it! The only request I have is to get functionality added into the `node_taint` module as well. Thanks 🎉

**Comment by sudermanjr** [comment]
> I like it! The only request I have is to get functionality added into the `node_taint` module as well. Thanks 🎉

I thought we were going to deprecate that module now?

**Comment by lucasreed** [comment]
> > I like it! The only request I have is to get functionality added into the `node_taint` module as well. Thanks 🎉
> 
> I thought we were going to deprecate that module now?

That's fair, we could do that instead!

**Review by lucasreed — APPROVED** [review]
Ignore the last review, as per Andy's comment we can deprecate the old module.

**Pull request merged**
